#!/bin/bash

# As input, this expects one or more TS-diskstats files as generated by pt-stalk
# To work, this depends on pt-diskstats being available on the path

HEADER='ts,device,rd_s,rd_avkb,rd_mb_s,rd_mrg,rd_cnc,rd_rt,wr_s,wr_avkb,wr_mb_s,wr_mrg,wr_cnc,wr_rt,busy,in_prg,io_s,qtime,stime'
INPUTFILE=/tmp/load_diskstats.$$
OUTPUTFILE=/tmp/output_diskstats.$$
TS=$(date "+%Y%m%d_%H%M_%S")
TABLE_NAME="pt_diskstats_$TS"

trap "rm -f $INPUTFILE $OUTPUTFILE RSCRIPT.$$ RSCRIPT.$$.Rout" SIGTERM EXIT

echo $HEADER>$OUTPUTFILE
# assume that if argc > 0 then args are diskstats files, else read from stdin
[ $# -gt 0 ] && {
	shift
	cat $*>$INPUTFILE	
} || {
	cat>$INPUTFILE
}

pt-diskstats $INPUTFILE|grep -v '^  #ts device'|grep -v ^$|sed 's/^  *//g'|sed 's/  */,/g'|tr -d '%'>>$OUTPUTFILE

cat<<EOF>RSCRIPT.$$
data <- read.table("$OUTPUTFILE",  header=TRUE, sep=",")
require(ggplot2)
png("genplot.png",height=800,width=800)
qplot(data=data, x=ts, y=busy, color=qtime)
dev.off()

EOF

R CMD BATCH ./RSCRIPT.$$


