#!/bin/bash 

# As input, this expects one more more TS-vmstat-overall files as generated by pt-stalk
# This is an example for how to graph multiple Y values over the same X

# TODO: labels


HEADER="seqno,r,b,swpd,free,buff,cache,si,so,bi,bo,in,cs,us,sy,id,wa,st"
OUTPUTFILE=/tmp/output_vmstat.$$

trap "rm -f $OUTPUTFILE RSCRIPT.$$ RSCRIPT.$$.Rout" SIGTERM EXIT

echo $HEADER>$OUTPUTFILE
# assume that if argc > 0 then args are vmstat files, else read from stdin
[ $# -gt 0 ] && {
	shift
	cat $* |egrep -v 'swpd|system'|grep -v ^$|sed 's/^  *//g'|sed 's/  */,/g'|awk '{print NR, ",", $0}'>>$OUTPUTFILE
} || {
	cat|egrep -v 'swpd|system'|grep -v ^$|sed 's/^  *//g'|sed 's/  */,/g'|awk '{print NR, ",", $0}'>>$OUTPUTFILE
}

cat<<EOF>RSCRIPT.$$
require(ggplot2)
data <- read.csv("$OUTPUTFILE", header=TRUE, sep=",")
png("vmstat_genplot.png",height=800,width=800)
ggplot(data=data, aes(x=seqno)) +
	geom_point(colour="red", aes(y=bi)) +
	geom_point(colour="blue", aes(y=bo)) +
	geom_point(colour="orange", aes(y=us+si+wa)) +
	geom_point(colour="yellow", aes(y=r+b))
dev.off()

EOF

R CMD BATCH ./RSCRIPT.$$

